version: '3.8'

services:
  postgresql:
    image: jvlr9510/debeziumpostgres:dev
    ports:
      - "5432:5432"
    hostname: postgresql
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "database_master"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
    command: ["postgres", "-c", "wal_level=logical"]

  api-autenticacao:
    image: jvlr9510/api-autenticacao:dev4
    ports:
      - "8081:8081"
    depends_on:
      - postgresql
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgresql:5432/database_master"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "admin"
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"
      SPRING_FLYWAY_TABLE: "schema_version_api_autenticacao"
      SERVER_PORT: "8081"

volumes:
   pg_data: {}

